# Generated by Django 5.0.4 on 2024-05-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_image',
        ),
    ]
