# Generated by Django 5.0.4 on 2024-05-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_branch_branch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/restaurants/'),
        ),
    ]
