# Generated by Django 5.0.4 on 2024-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branch_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/branches/'),
        ),
    ]
