# Generated by Django 5.0.4 on 2024-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_alter_branch_branch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(blank=True, null=True, upload_to='branches'),
        ),
    ]
